version: '3'

services:
    nginx:
        build: 
            context: ./php-nginx/nginx/
            args: 
                - NGINX_VERSION=${NGINX_VERSION}
        image: nginx
        restart: unless-stopped
        ports:
            # 本機port:Container的Port
            # - '8088:80'
            - '${NGINX_PORT}:80'
        # depends_on php
        depends_on:
            - 'php'
        volumes:
            # 對應主機./conf.d目錄到容器/etc/nginx/conf.d目錄
            - "./php-nginx/nginx/conf.d:/etc/nginx/conf.d"
            # './{本地web資料夾(可自定義)}:/var/www/html/{your-project}'
            - "./web:/var/www/html/${PROJECT_NAME}"
        container_name: "${NGINX_CONTAINER_NAME}"
    php:
        build: 
            context: ./php-nginx/php
            args: 
                - PHP_VERSION=${PHP_VERSION}
        # image指定build Dockerfile產生Container的名稱
        image: php
        restart: unless-stopped
        ports:
            # '本機port:Container的Port'
            # - '9000:9000'
            - '${PHP_PORT}:9000'
        volumes:
            # 掛載
            - "./web:/var/www/html/${PROJECT_NAME}"
        container_name: "${PHP_CONTAINER_NAME}"
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: unless-stopped
        ports:
            # 本機Port:Container的Port
            # - '3309:3306'
            - '${MYSQL_PORT}:3306'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        container_name: "${MYSQL_CONTAINER_NAME}"
